/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// InlineResponse200Items struct for InlineResponse200Items
type InlineResponse200Items struct {
	// The name of the workflow.
	Name string `json:"name"`
	// The start of the aggregation window for workflow metrics.
	WindowStart time.Time `json:"window_start"`
	// The end of the aggregation window for workflow metrics.
	WindowEnd time.Time                `json:"window_end"`
	Metrics   InlineResponse200Metrics `json:"metrics"`
}
