/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// InlineResponseDefault struct for InlineResponseDefault
type InlineResponseDefault struct {
	Message string `json:"message,omitempty"`
}
