/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PipelineConfig The configuration strings for the pipeline.
type PipelineConfig struct {
	// The source configuration for the pipeline, before any config compilation has been performed. If there is no config, then this field will be empty.
	Source string `json:"source"`
	// The compiled configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's configuration, then this field may be empty.
	Compiled string `json:"compiled"`
}
