/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// RerunWorkflowParameters The information you can supply when rerunning a workflow.
type RerunWorkflowParameters struct {
	// A list of job IDs to rerun.
	Jobs []string `json:"jobs,omitempty"`
	// Whether to rerun the workflow from the failed job. Mutually exclusive with the jobs parameter.
	FromFailed bool `json:"from_failed,omitempty"`
}
