/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// Pipeline A pipeline response.
type Pipeline struct {
	// The unique ID of the pipeline.
	Id string `json:"id"`
	// A sequence of errors that have occurred within the pipeline.
	Errors []PipelineListResponseErrors `json:"errors"`
	// The project-slug for the pipeline.
	ProjectSlug string `json:"project_slug"`
	// The date and time the pipeline was last updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The number of the pipeline.
	Number int64 `json:"number"`
	// The current state of the pipeline.
	State string `json:"state"`
	// The date and time the pipeline was created.
	CreatedAt time.Time                   `json:"created_at"`
	Trigger   PipelineListResponseTrigger `json:"trigger"`
	Vcs       PipelineListResponseVcs     `json:"vcs,omitempty"`
}
