/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Project NOTE: The definition of Project is subject to change.
type Project struct {
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
	Slug string `json:"slug"`
	// The name of the project
	Name string `json:"name"`
	// The name of the organization the project belongs to
	OrganizationName string         `json:"organization_name"`
	VcsInfo          ProjectVcsInfo `json:"vcs_info"`
}
