/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// PipelineCreation A pipeline creation response.
type PipelineCreation struct {
	// The unique ID of the pipeline.
	Id string `json:"id"`
	// The current state of the pipeline.
	State string `json:"state"`
	// The number of the pipeline.
	Number int64 `json:"number"`
	// The date and time the pipeline was created.
	CreatedAt time.Time `json:"created_at"`
}
