/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// Workflow A workflow
type Workflow struct {
	// The ID of the pipeline this workflow belongs to.
	PipelineId string `json:"pipeline_id"`
	CanceledBy string `json:"canceled_by,omitempty"`
	// The unique ID of the workflow.
	Id string `json:"id"`
	// The name of the workflow.
	Name string `json:"name"`
	// The project-slug for the pipeline this workflow belongs to.
	ProjectSlug string `json:"project_slug"`
	ErroredBy   string `json:"errored_by,omitempty"`
	// The current status of the workflow.
	Status    string `json:"status"`
	StartedBy string `json:"started_by"`
	// The number of the pipeline this workflow belongs to.
	PipelineNumber int64 `json:"pipeline_number"`
	// The date and time the workflow was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the workflow stopped.
	StoppedAt time.Time `json:"stopped_at"`
}
