/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PipelineListResponseTriggerActor The user who triggered the Pipeline.
type PipelineListResponseTriggerActor struct {
	// The login information for the user on the VCS.
	Login string `json:"login"`
	// URL to the user's avatar on the VCS
	AvatarUrl string `json:"avatar_url"`
}
