/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// PipelineListResponseTrigger A summary of the trigger.
type PipelineListResponseTrigger struct {
	// The type of trigger.
	Type string `json:"type"`
	// The date and time the trigger was received.
	ReceivedAt time.Time                        `json:"received_at"`
	Actor      PipelineListResponseTriggerActor `json:"actor"`
}
