/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// MessageResponse message response
type MessageResponse struct {
	// A human-readable message
	Message string `json:"message"`
}
