/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// InlineResponse2003Items struct for InlineResponse2003Items
type InlineResponse2003Items struct {
	// The unique ID of the job.
	Id string `json:"id"`
	// The date and time the job started.
	StartedAt time.Time `json:"started_at"`
	// The time when the job stopped.
	StoppedAt time.Time `json:"stopped_at"`
	// Job status.
	Status string `json:"status"`
	// The number of credits used during execution
	CreditsUsed int64 `json:"credits_used"`
}
