/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PipelineListResponseErrors An error with a type and message.
type PipelineListResponseErrors struct {
	// The type of error.
	Type string `json:"type"`
	// A human-readable error message.
	Message string `json:"message"`
}
