/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// CheckoutKeyInput struct for CheckoutKeyInput
type CheckoutKeyInput struct {
	// The type of checkout key to create. This may be either `deploy-key` or `user-key`.
	Type string `json:"type"`
}
