/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PipelineListResponseVcsCommit The latest commit in the pipeline.
type PipelineListResponseVcsCommit struct {
	// The subject of the commit message.
	Subject string `json:"subject"`
	// The body of the commit message.
	Body string `json:"body"`
}
